eureka:
  image: eureka
  ports:
    - "8761:8761"

demoone:
  image: demoone
  ports:
    - "9001:9001"
  links:
    - eureka

demotwo:
  image: demotwo
  ports:
    - "9002:9002"
  links:
    - eureka
    - demoone